processing:
  clean:
    patterns:
      - '^\(.*?\) '
      - ',.*$'
    remove_words:
      - 'low-fat'
      - 'lowfat'
      - 'low fat'
      - 'sodium'
      - 'lb\.'
      - 'ounc'
      - 'fresh'
    cuisine_attr: "cuisine"
    ingredients_attr": "ingredients"
    cuisine_col: "cuisine"
    ingredient_col: "ingredient"
  features:
    drop_rows:
      - 'salt'
      - 'water'
      - 'sugar'
      - 'olive oil'
      - 'garlic cloves'
    min_prevalence: 100
    sum_column: 'ingr_sum'
model:
  initialize:
    num_guesses: 3
    num_ingredients: 5
  train:
    scale_const: 1000
    sum_column: 'ingr_sum'
  evaluate:
    splits:
      random_state: 666
      train_size: 0.8
      

