processing:
  clean:
    PATTERNS:
      - '^\(.*?\) '
      - ',.*$'
    REMOVE_WORDS:
      - 'low-fat'
      - 'lowfat'
      - 'low fat'
      - 'sodium'
      - 'lb\.'
      - 'ounc'
      - 'fresh'
  features:
    DROP_ROWS:
      - 'salt'
      - 'water'
      - 'sugar'
      - 'olive oil'
      - 'garlic cloves'
    MIN_PREVALENCE: 100
model:
  initialize:
    NUM_GUESSES: 3
    NUM_INGREDIENTS: 5
  train:
    SCALE_CONST: 1000
    SUM_COLUMN: 'ingr_sum'
  evaluate:
    splits:
      train_size: 0.8

